
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
spec:
  capacity:
    storage: {{ .Values.storage.fmeserver.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storage.nfs.serverIP }}
    path: "/data"