apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    safe.k8s.fmeserver.build: {{ .Values.fmeserver.buildNr }}
    safe.k8s.fmeserver.component: engine
    safe.k8s.fmeserver.set.id: {{ .Values.fmeserver.engines.defaultSetID }}
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      safe.k8s.fmeserver.component: engine
  template:
    metadata:
      labels:
        safe.k8s.fmeserver.component: engine
        safe.k8s.fmeserver.build: {{ .Values.fmeserver.buildNr }}
    spec:
      containers:
        - image: safe-harbor.safe.internal/fmeserver-kubernetes/fmeserver-engine:{{ .Values.fmeserver.buildNr }}
          name: engine
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          volumeMounts:
            - mountPath: /data/fmeserverdata
              name: fmeserverdata
          env:
            - name: EXTERNALHOSTNAME
              value: {{ .Values.deployment.hostname }}
            - name: WEBPROTOCOL
              value: https
            - name: EXTERNALPORT
              value: '443'
            - name: FMESERVERHOSTNAME
              value: engineregistration
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always
      volumes:
        - name: fmeserverdata
          persistentVolumeClaim:
            claimName: fmeserver-data-{{ .Values.fmeserver.buildNr }}