apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    safe.k8s.fmeserver.build: "{{ .Values.fmeserver.buildNr }}"
    safe.k8s.fmeserver.component: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      safe.k8s.fmeserver.component: queue
  serviceName: fmeserverqueue
  template:
    metadata:
      labels:
        safe.k8s.fmeserver.component: queue
        safe.k8s.fmeserver.build: "{{ .Values.fmeserver.buildNr }}"
    spec:
      containers:
        - image: safe-harbor.safe.internal/fmeserver-kubernetes/fmeserver-queue:{{ .Values.fmeserver.buildNr }}
          name: queue
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data/fmeserverdata
              name: fmeserverdata
          env:
          - name: POD_IP
            valueFrom: { fieldRef: { fieldPath: status.podIP } }
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec redis-cli -a sozPpbLfgdI9WJoPejNMpSxGw -h $POD_IP ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec redis-cli -a sozPpbLfgdI9WJoPejNMpSxGw -h $POD_IP ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 5
      restartPolicy: Always
      volumes:
        - name: fmeserverdata
          persistentVolumeClaim:
            claimName: fmeserver-data-{{ .Values.fmeserver.buildNr }}