apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    safe.k8s.fmeserver.component: db
    {{- include "fmeserver.common.labels" . | indent 4 }}
  name: fmeserver-db-{{ .Values.fmeserver.buildNr }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if not .Values.storage.useHostDir }}
  storageClassName: {{.Values.storage.database.class}}
  {{- end }}
  resources:
    requests:
      storage: {{.Values.storage.database.size}}
