apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    safe.k8s.fmeserver.component: misc
    {{- include "fmeserver.common.labels" . | indent 4 }}
  name: fmeserver-data
spec:
  accessModes:
  - ReadWriteOnce
  {{- if and (not .Values.storage.useHostDir) .Values.storage.fmeserver.class }}
  storageClassName: {{.Values.storage.fmeserver.class}}
  {{- end }}
  resources:
    requests:
      storage: {{.Values.storage.fmeserver.size}}
