# This configuration is heavily inspired by the official helm chart (https://github.com/kubernetes/charts/tree/master/stable/nfs-server-provisioner)
{{ if .Values.storage.deployNFS }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nfs-provisioner.fullName" . }}
  labels:
    safe.k8s.fmeserver.component: nfs
    {{- include "fmeserver.common.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["nfs-provisioner"]
    verbs: ["use"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "nfs-provisioner.fullName" . }}
  labels:
    safe.k8s.fmeserver.component: nfs
    {{- include "fmeserver.common.labels" . | indent 4 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nfs-provisioner.fullName" . }}
  labels:
    safe.k8s.fmeserver.component: nfs
    {{- include "fmeserver.common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nfs-provisioner.fullName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs-provisioner.fullName" . }}
    namespace: {{ .Release.Namespace }}
---
kind: Service
apiVersion: v1
metadata:
  name: fmeserverdata-nfs
  labels:
    safe.k8s.fmeserver.component: nfs
    {{- include "fmeserver.common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    safe.k8s.fmeserver.component: nfs
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  serviceName: fmeserverdata-nfs
  replicas: 1
  selector:
    matchLabels:
      safe.k8s.fmeserver.component: nfs
  template:
    metadata:
      labels:
        safe.k8s.fmeserver.component: nfs
        {{- include "fmeserver.common.labels" . | indent 8 }}
    spec:
      # NOTE: This is 10 seconds longer than the default nfs-provisioner --grace-period value of 90sec
      terminationGracePeriodSeconds: 100
      serviceAccountName: {{ template "nfs-provisioner.fullName" . }}
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.9
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner={{ template "nfs-provisioner.provisionerName" . }}"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: fmeserverdata-nfs
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: fmeserverdata
              mountPath: /export
      volumes:
        - name: fmeserverdata
          persistentVolumeClaim:
            claimName: fmeserver-data
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "nfs-provisioner.fullName" . }}
  labels:
    safe.k8s.fmeserver.component: nfs
    {{- include "fmeserver.common.labels" . | indent 4 }}
provisioner: {{ template "nfs-provisioner.provisionerName" . }}
parameters:
  gid: "1363"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fmeserver-data-nfs
  labels:
    safe.k8s.fmeserver.component: data
    {{- include "fmeserver.common.labels" . | indent 4 }}
spec:
  storageClassName: {{ template "nfs-provisioner.fullName" . }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.fmeserver.nfsClaimSize | default .Values.storage.fmeserver.size }}
{{ end }}