apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    safe.k8s.fmeserver.build: {{ required "A published fmeserver.buildNr needs to be passed in." .Values.fmeserver.buildNr | quote }}
    safe.k8s.fmeserver.component: misc
  name: fmeserver-data-{{ required "A published fmeserver.buildNr needs to be passed in." .Values.fmeserver.buildNr }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if not .Values.storage.useHostDir }}
  storageClassName: {{.Values.storage.fmeserver.class}}
  {{- end }}
  resources:
    requests:
      storage: {{.Values.storage.fmeserver.size}}
