{{- if not .Values.fmeserver.database.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fmeserver.fullname" . }}
  labels:
    app: {{ template "fmeserver.name" . }}
    chart: {{ template "fmeserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  fmeserver-db-password: {{ .Values.fmeserver.database.password | b64enc | quote }}
{{- end -}}