apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name}}-deployment-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - image: {{ .Values.images.registry }}/{{ .Values.images.namespace }}/fmeserver-deployment-tester:{{ .Values.fmeserver.buildNr }}
      name: deployment-tester
      env:
        - name: FMESERVER_URL
          value: "https://{{ .Values.deployment.hostname }}"
        - name: FMESERVER_USER
          value: "admin"
        - name: FMESERVER_PASSWORD
          value: "admin"
  hostNetwork: true
  restartPolicy: Never