apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fmeserver-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.deployment.proxyReadTimeout | quote }}
{{- include "fmeserver.ingress.annotations" . | indent 4 }}
spec:
  {{- include "fmeserver.ingress.tls" . }}
  rules:
    {{- if .Values.deployment.useHostnameIngress }}
    - host: {{ .Values.deployment.hostname }}
      {{ else }}
    - {{ end }}http:
        paths:
          - backend:
              serviceName: fmeserverweb
              servicePort: 8080
            path: /