fmeserver:
  buildNr:

deployment:
  hostname: localhost
  proxyReadTimeout: 60
  tlsSecretName:
  certManager:
    issuerName:
    issuerType: cluster
  numCores: 1
  numEngines: 2
  startAsRoot: false
  singleServiceIngress: false

resources:
  core:
    requests:
      memory: 2Gi
      cpu: 200m
  engine:
    requests:
      memory: 512Mi
      cpu: 200m
  queue:
    requests:
      memory: 128Mi
      cpu: 100m
  websocket:
    requests:
      memory: 256Mi
      cpu: 100m

storage:
  useHostDir: false
  reclaimPolicy: Delete
  postgresql:
    size: 1Gi
    class:
    path:
  fmeserver:
    accessMode: ReadWriteOnce
    size: 10Gi
    class:
    path:

images:
  # Supported values: Always or IfNotPresent
  pullPolicy: IfNotPresent
  registry: quay.io
  namespace: safesoftware

# It is recommended not to modify those parameters
# For more options regarding PostgreSQL deployement, check the helm chart documentation:
# https://github.com/kubernetes/charts/tree/master/stable/postgresql
postgresql:
  postgresDatabase: fmeserver
  postgresUser: fmeserver
  # TODO: Remove and use autogenerated PW once containers support it.
  postgresPassword: fmeserver
  persistence:
    existingClaim: fmeserver-postgresql
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
