fmeserver:
  buildNr:
  database:
    host:
    port: '5432'
    name: fmeserver
    user: fmeserver
    
    # This user and password must be a database user that can create databases and users in the postgresql database
    adminUser: postgres
    adminPasswordSecret:
    adminPasswordSecretKey:  postgresql-password

deployment:
  hostname: localhost
  proxyReadTimeout: 60
  tlsSecretName:
  certManager:
    issuerName:
    issuerType: cluster
  numCores: 1
  numEngines: 2
  startAsRoot: false
  useHostnameIngress: true
  deployPostgresql: true

scheduling:
  core:
    affinity: {}
    nodeSelector: {}
    tolerations: []
  engine:
    affinity: {}
    nodeSelector: {}
    tolerations: []
  queue:
    affinity: {}
    nodeSelector: {}
    tolerations: []
  websocket:
    affinity: {}
    nodeSelector: {}
    tolerations: []

resources:
  core:
    requests:
      memory: 2Gi
      cpu: 200m
  engine:
    requests:
      memory: 512Mi
      cpu: 200m
  queue:
    requests:
      memory: 128Mi
      cpu: 100m
  websocket:
    requests:
      memory: 256Mi
      cpu: 100m

storage:
  useHostDir: false
  reclaimPolicy: Delete
  postgresql:
    size: 1Gi
    class:
    path:
  fmeserver:
    accessMode: ReadWriteOnce
    size: 10Gi
    class:
    path:

images:
  # Supported values: Always or IfNotPresent
  pullPolicy: IfNotPresent
  registry: quay.io
  namespace: safesoftware

# It is recommended not to modify those parameters
# For more options regarding PostgreSQL deployement, check the helm chart documentation:
# https://github.com/kubernetes/charts/tree/master/stable/postgresql
postgresql:
  persistence:
    existingClaim: fmeserver-postgresql
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
